- menu_name: "Anexos"

- name: "Contacto"
  url: "/contacto/"
  title: "Contacto"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribete con RSS"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribete con Atom"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
