- menu_name: "Anexos"

- name: "Contacto"
  url: "/contacto/"
  title: "Contacto"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscríbete al feed RSS"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscríbete al feed Atom"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap para Google Webmaster Tools"
